### ISSUE TITLE
groupby only grouping consecutive occurrences

### ISSUE THREAD

**Issue by cgroll** [JuliaLang/Iterators.jl#23]
I want to group tuples with respect to a common second entry. however, the following code 

``` julia
valuePairs = [(:A, :Hello),
              (:B, :Bye),
              (:C, :Hello),
              (:D, :Hello),
              (:E, :Bye),
              (:F, :Bye),
              (:G, :Hello),
              (:H, :Bye)]
kk = Iterators.groupby(valuePairs, x -> x[2])
for ii in kk
    @show ii
end
```

displays

``` julia
ii => [(:A,:Hello)]
ii => [(:B,:Bye)]
ii => [(:C,:Hello),(:D,:Hello)]
ii => [(:E,:Bye),(:F,:Bye)]
ii => [(:G,:Hello)]
ii => [(:H,:Bye)]
```

Is this intended? I'd expect tuples to be split in two groups only: those showing :Hello as first entry, and those showing :Bye.

**Comment by oxinabox** [comment]
The following languages **do **require consecutive (as is the current state of Iterators.jl):
 -  [Rust](https://bluss.github.io/rust-itertools/doc/itertools/trait.Itertools.html#method.group_by)
 - [Haskell](http://zvon.org/other/haskell/Outputlist/groupBy_f.html)



The following languages **do not **care about concecutive (and have this method in there Iterators type library)
 - [Python](https://docs.python.org/2/library/itertools.html#itertools.groupby)
 - [.Net/C#, F#, VB etc](https://msdn.microsoft.com/library/bb534304%28v=vs.100%29.aspx)
 - [Groovy](http://docs.groovy-lang.org/docs/groovy-1.7.3/html/groovy-jdk/java/util/Collection.html#groupBy%28groovy.lang.Closure%29)
 - [Scalar](http://markusjais.com/the-groupby-method-from-scalas-collection-library/) , I'm not sure if this is in an iterators  type library or not, Scalr doc is so hard to read, so I'm linking to a tutorial page.

The following **do not **care about consecutive, and have this in their core library:
 - [Mathematica](https://reference.wolfram.com/language/ref/GroupBy.html)
 - [clojure](https://clojuredocs.org/clojure.core/group-by), you may have been thinking of [partition-by](https://clojuredocs.org/clojure.core/partition


I'm not sure if I would suggest changing the method or not, since it is definitely a breaking change.
But I would suggest that not requiring consecutive is the more common approach

**Comment by kmsquire** [comment]
> The following languages do not care about consecutive (and have this method in there Iterators type library)

> * Python

Actually, Python does care that the values are consecutive:

```python
In [7]: valuePairs = [("A", "Hello"), ("B", "Bye"), ("C", "Hello"), ("D", "Hello"), ("E", "Bye"), ("F", "Bye"), ("G", "Hello")]

In [8]: [(x[0], list(x[1])) for x in groupby(valuePairs, lambda x: x[1])]
Out[8]:
[('Hello', [('A', 'Hello')]),
 ('Bye', [('B', 'Bye')]),
 ('Hello', [('C', 'Hello'), ('D', 'Hello')]),
 ('Bye', [('E', 'Bye'), ('F', 'Bye')]),
 ('Hello', [('G', 'Hello')])]
```

**Comment by oxinabox** [comment]
Oops. Fixed.
